# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capucine"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Damian Le Nouaille"]
  s.date = "2012-03-01"
  s.description = "longer description of your gem"
  s.email = "dam@dln.name"
  s.executables = ["capucine"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/capucine",
    "content/shared/coffeescript/app.coffee",
    "content/shared/css/import/YOUR_OLD_CSS",
    "content/shared/images/favicon/apple-touch-icon-114x114-precomposed.png",
    "content/shared/images/favicon/apple-touch-icon-57x57-precomposed.png",
    "content/shared/images/favicon/apple-touch-icon-72x72-precomposed.png",
    "content/shared/images/favicon/apple-touch-icon-precomposed.png",
    "content/shared/images/favicon/favicon.png",
    "content/shared/js/app.js",
    "content/shared/sass/_main.sass",
    "content/shared/sass/_responsive.sass",
    "content/shared/sass/screen.sass",
    "content/shared/templates/_footer.html",
    "content/shared/templates/_header.html",
    "content/shared/templates/index.html.erb",
    "content/templates/capucine.yaml",
    "content/templates/cmd_help.erb",
    "content/templates/compass_config.erb",
    "lib/capucine.rb",
    "lib/coffeescript.rb",
    "lib/commands.rb",
    "lib/compass-sass.rb",
    "lib/incloudr.rb",
    "lib/settings.rb",
    "lib/templates.rb",
    "lib/tools.rb",
    "lib/watch.rb"
  ]
  s.homepage = "http://capucine.dln.name"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Tools for frontend developers. Use CoffeeScript and Compass everywhere."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fssm>, [">= 0"])
      s.add_runtime_dependency(%q<compass>, ["= 0.12.rc.0"])
      s.add_runtime_dependency(%q<coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<uglifier>, [">= 0"])
      s.add_runtime_dependency(%q<packr>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<fssm>, [">= 0"])
      s.add_dependency(%q<compass>, ["= 0.12.rc.0"])
      s.add_dependency(%q<coffee-script>, [">= 0"])
      s.add_dependency(%q<uglifier>, [">= 0"])
      s.add_dependency(%q<packr>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<fssm>, [">= 0"])
    s.add_dependency(%q<compass>, ["= 0.12.rc.0"])
    s.add_dependency(%q<coffee-script>, [">= 0"])
    s.add_dependency(%q<uglifier>, [">= 0"])
    s.add_dependency(%q<packr>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

